# Generated by Django 5.2.6 on 2025-09-08 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.CharField(help_text='Identificador único del registro', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del registro', max_length=255)),
                ('categoria', models.CharField(blank=True, help_text='Categoría del registro (opcional)', max_length=120, null=True)),
                ('fecha', models.DateField(blank=True, help_text='Fecha asociada al registro (opcional)', null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor monetario o numérico (opcional)', max_digits=12, null=True)),
                ('lat', models.FloatField(blank=True, help_text='Latitud de la ubicación (opcional, -90 a 90)', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lon', models.FloatField(blank=True, help_text='Longitud de la ubicación (opcional, -180 a 180)', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'indexes': [models.Index(fields=['categoria'], name='api_registr_categor_dff2f3_idx'), models.Index(fields=['lat', 'lon'], name='api_registr_lat_a2eceb_idx')],
            },
        ),
    ]
