# Generated by Django 5.2.6 on 2025-09-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=120)),
                ('shelf', models.CharField(blank=True, max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='catalog_boo_code_1a91ca_idx'), models.Index(fields=['author'], name='catalog_boo_author_66025a_idx'), models.Index(fields=['area'], name='catalog_boo_area_9ae581_idx'), models.Index(fields=['title'], name='catalog_boo_title_3a1ffe_idx')],
            },
        ),
    ]
